plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
}

android {
    namespace = "com.ccko.pikxplus"
    compileSdk = 36
    
    defaultConfig {
        applicationId = "com.ccko.pikxplus"
        minSdk = 30
        targetSdk = 34
        versionCode = 1
        versionName = "1.2"
        
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables { 
            useSupportLibrary = true
        }
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    buildFeatures {
    viewBinding = true
    buildConfig = true
    }
    
}

configurations.all {
    resolutionStrategy {
        force("org.jetbrains.kotlin:kotlin-stdlib:1.8.21")
        force("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21")
    }
}
dependencies {
    // AndroidX
    implementation("androidx.core:core-ktx:1.10.1")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")

    // Material Design
    implementation("com.google.android.material:material:1.9.0")

    // Navigation Component
    implementation("androidx.navigation:navigation-fragment-ktx:2.6.0")
    implementation("androidx.navigation:navigation-ui-ktx:2.6.0")

    // Lifecycle components (ViewModel, LiveData)
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1")
    implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.6.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.6.1")

    // RecyclerView
    implementation("androidx.recyclerview:recyclerview:1.4.0")
		
		 // Testing
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    
    // For image loading without external libraries
    implementation("androidx.exifinterface:exifinterface:1.3.3")
    implementation("com.github.bumptech.glide:glide:4.13.2")

    implementation ("com.google.android.exoplayer:exoplayer:2.19.1")
	
//	implementation("androidx.core:core:1.17.0")
 // implementation("androidx.appcompat:appcompat:1.7.1")
  

    // Glide for image loading
 //   implementation("com.github.bumptech.glide:glide:4.15.1")
   // annotationProcessor("com.github.bumptech.glide:compiler:4.15.1")
    // WebP decoder integration that matches Glide 4.15.1
  //  implementation("com.github.zjupure:webpdecoder:2.4.4.15.1")

    // ExoPlayer (Media3)
    //implementation("androidx.media3:media3-exoplayer:1.1.0")
   // implementation("androidx.media3:media3-ui:1.1.0")

   
}
